version: "3.8"

services:
  # Database
  db:
    image: postgres:15
    container_name: quiz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-quizdb}
      POSTGRES_USER: ${DB_USERNAME:-quizuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-quizpass}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb/01-init-schema.sql:/docker-entrypoint-initdb.d/01-init-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizuser -d quizdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7
    container_name: quiz_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MinIO Object Storage
  minio:
    image: minio/minio
    container_name: quiz_minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data

volumes:
  db_data:
  redis_data:
  minio_data: